### ISSUE TITLE
'Vehicles And Fuel Tanks' figure is off by ~5000 the last few days

### ISSUE THREAD

**Issue by ovitters** [davidchoo12/russias-losses#3]
The last few days the Vehicles And Fuel Tanks figure doesn't match the source figure. It sometimes goes down with ~5000 or so. Not exactly sure how it reads the figure wrong, it doesn't just forget the first number for instance.

Could you please fix it, perhaps also correct the days that are off?

Thanks for the site!

**Comment by davidchoo12** [comment]
fixed in dd48480
