### ISSUE TITLE
Graphs do not show data when switching to "Last 7 days" or "Last 30 days"

### ISSUE THREAD

**Issue by usr20210909** [davidchoo12/russias-losses#4]
This relates to https://russiaslosses.netlify.app/

When selecting **`All time`** the graph is OK:
![image](https://github.com/davidchoo12/russias-losses/assets/90362157/341b4f58-137f-42a7-8a06-b6eed7c24889)

When selecting **`Last 7 days`** or **`Last 30 days`** no data is shown and the x-axis (time) does not correspond to the selection:
![image](https://github.com/davidchoo12/russias-losses/assets/90362157/7f9977e5-ded2-46cc-a62a-6a8fd8760a23)
![image](https://github.com/davidchoo12/russias-losses/assets/90362157/150d4a9e-205b-4c2c-b80b-b061d6d0fd14)

**Comment by usr20210909** [comment]
It has stopped getting new data after 2023-04-20:

![image](https://github.com/davidchoo12/russias-losses/assets/90362157/94b406cc-30f0-4b5d-b0fb-c7acf8131976)

https://russiaslosses.netlify.app/

**Comment by davidchoo12** [comment]
Fixed, data was missing due to twitter removing free api access, I'm now scraping from facebook instead
